
[build.environment]
  NODE_VERSION = "20"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/2023-06-14/unocss-best-practice/"
  to = "https://talks.zyob.top/2023-06-14/unocss-best-practice/"
  status = 301
  
[[redirects]]
  from = "/2023-06-14/unocss-best-practice/*"
  to = "/2023-06-14/unocss-best-practice/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://zyob.top"
  status = 302
